; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
; https://github.com/handledexception/platform-espressif32/blob/esp32-s3-devkitc-1-n16r8v/boards/esp32-s3-devkitc-1-n16r8v.json
; https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/hw-reference/esp32s3/user-guide-devkitc-1.html

[env:svems]
platform = espressif32
board = esp32-s3-devkitc-1-n16r8v
framework = arduino
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_upload.flash_size = 16MB
board_build.flash_size = 16MB
board_build.f_flash = 80000000L
board_build.f_cpu = 240000000L
monitor_speed = 115200
upload_speed = 921600
build_flags = 
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DBOARD_HAS_PSRAM
	-DARDUINO_ESP32S3_DEV
	-DCORE_DEBUG_LEVEL=3
	-mfix-esp32-psram-cache-issue
	-std=gnu++17
monitor_filters = 
    esp32_exception_decoder
lib_deps =
	adafruit/Adafruit NeoPixel @ ^1.15.5
build_unflags =
	-std=gnu++11
